// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table TaxiEvents (VendorID:int, tpep_pickup_datetime:datetime, tpep_dropoff_datetime:datetime, passenger_count:int, trip_distance:real, RatecodeID:int, store_and_fwd_flag:string, PULocationID:int, DOLocationID:int, payment_type:int, fare_amount:real, extra:real, mta_tax:real, tip_amount:real, tolls_amount:real, improvement_surcharge:real, total_amount:real, congestion_surcharge:real, airport_fee:real) 
.create-or-alter materialized-view  TaxiFareByMinute on table TaxiEvents { TaxiEvents
    | summarize
        trip_count=count(),
        total_revenue=sum(total_amount),
        average_fare=avg(fare_amount),
        max_fare=max(fare_amount)
      by pickup_minute=bin(tpep_pickup_datetime, 1m), PULocationID }
.alter table TaxiEvents policy retention @'{"SoftDeletePeriod":"30.00:00:00","Recoverability":"Enabled"}'
